# -*- coding: utf-8 -*-
"""Phyton project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvowUL1acCJycUoUZKE80UetnVd4U7lM

**TO import.csv dataset into Phyton**
"""

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from google.colab import drive

df  = pd.read_csv('/content/sample_data/Employee_Details.csv')
df.head()

import pandas as pd

# Sample Data
df = pd.DataFrame({'last_login': ['2025-07-06 15:30:00', '2025-07-07 09:15:00']})

# 1. Convert to datetime
df['last_login'] = pd.to_datetime(df['last_login'])

# 2. Extract Date and Time
df['login_date'] = df['last_login'].dt.date
df['login_time'] = df['last_login'].dt.time

print(df)

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from google.colab import drive

df_employee_health  = pd.read_csv('/content/sample_data/Employee_Health.csv')
df_employee_health.head()

# Removing duplicates(dropping row)
df_employee_health = df_employee_health.drop_duplicates()

df_employee_health

df = df.drop_duplicates()
df

# Removing duplicates (dropping row)
df = df.drop_duplicates()
df

# Replace non-alphanumeric and non-whitespace characters with an empty string
df['Name'] = df['Name'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)

print("/content/sample_data/Employee_Details.csv")
print(df)

# Replace non-alphanumeric and non-whitespace characters with an empty string
df['Name'] = df['Name'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)

print('/content/sample_data/Employee_Health.csv')
print(df)

import pandas as pd

# Sample DataFrame (replace with your actual data)
df = pd.DataFrame({'Smoking': ['Yes', 'No', 'Yes', 'No', 'Yes', 'Maybe']})

# Define the mapping
smoking_mapping = {'Yes': 1, 'No': 0}

# Apply the mapping to the column
df['Smoking_Numeric'] = df['Smoking'].map(smoking_mapping)

print(df)

import pandas as pd

# Sample Data
df = pd.DataFrame({'last_login': ['2025-07-06 15:30:00', '2025-07-07 09:15:00']})

# 1. Convert to datetime
df['last_login'] = pd.to_datetime(df['last_login'])

# 2. Extract Date and Time
df['login_date'] = df['last_login'].dt.date
df['login_time'] = df['last_login'].dt.time

print(df)

df['Department'] = df['Department'].str.upper()
df

df['Department'] = df['Department'].fillna('unknown department')
df['Department']

"""**#NUMPY**"""

import statistics

# Sample Data
ages = [30, 45, 22, 35, 50]
stress_levels = [5, 8, 3, 7, 6]  # Scale 1-10

# Calculate Means
mean_age = statistics.mean(ages)
mean_stress = statistics.mean(stress_levels)

print(f"Average Age: {mean_age}")
print(f"Average Stress Level: {mean_stress}")

import numpy as np

# Sample Data: [Age, StressLevel (1-10)]
employees = np.array([
    [25, 3],
    [30, 7],
    [35, 5],
    [40, 8],
    [22, 2]
])

# 1. Calculate average of each column (Age and StressLevel)
# Axis 0 = column-wise mean
avg_age, avg_stress = np.mean(employees, axis=0)

print(f"Average Age: {avg_age}")
print(f"Average Stress Level: {avg_stress}")

# Alternative: If data is in separate arrays
# ages = np.array([25, 30, 35, 40, 22])
# print(np.mean(ages))

import numpy as np

work_hours = [7.5, 8.0, 6.5, 9.0, 7.0, 8.5]

median_hours = np.median(work_hours)

print(f"The median work hours are: {median_hours}")

import numpy as np

# Create a NumPy array of sleep hours (in hours)
# Example data: [7.5, 6.0, 8.2, 5.5, 7.0, 6.5]
sleep_hours = np.array([7.5, 6.0, 8.2, 5.5, 7.0, 6.5])

# Method 1: Use the np.min() function
min_hours_func = np.min(sleep_hours)

# Method 2: Use the .min() method on the array
min_hours_method = sleep_hours.min()

# Print the minimum sleep hours
print(f"The minimum sleep hours using np.min() is: {min_hours_func} hours")
print(f"The minimum sleep hours using .min() method is: {min_hours_method} hours")

import numpy as np

steps = np.array([13729, 13760, 10161, 14997, 4472])
max_steps = np.max(steps)
print(max_steps)  # Output: 15000

"""# MARGE"""

import pandas as pd

# Create sample DataFrames (df1 and df2)
df1 = pd.DataFrame({
    'Key': ['A', 'B', 'C'],
    'Value1': [1, 2, 3]
})

df2 = pd.DataFrame({
    'Key': ['B', 'C', 'D'],
    'Value2': [4, 5, 6]
})

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# Perform an outer merge
merged_outer_df = pd.merge(df1, df2, how='outer', on='Key')

print("\nOuter Merged DataFrame:")
print(merged_outer_df)

import pandas as pd

# Create the first DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

# Create the second DataFrame with some overlapping IDs
df2 = pd.DataFrame({
    'ID': [3, 4, 5, 6],
    'Age': [25, 30, 22, 35]
})

# Perform an inner join on the 'ID' column
# 'how="inner"' is optional as it is the default
merged_inner = pd.merge(df1, df2, on='ID', how='inner')

# Print the result
print(merged_inner)

import pandas as pd

data = {
    'Department': ['HR', 'Finance', 'Marketing', 'IT', 'Operation', 'IT'],
    'Employee': ['Megan', 'Thomas', 'William', 'Rebecca', 'Juan', 'Kyle'],
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

import pandas as pd

# Sample DataFrame
data = {'Employee': ['Megan', 'Katherine', 'Robert', 'Jonathan','Katelyn','Christine','Craig','Ryan','Thomas','Michelle'], 'Productivity score': [43, 85, 76, 74, 60, 99, 68, 96, 85, 93]}
df = pd.DataFrame(data)

# Sort descending (Highest score first)
sorted_df = df.sort_values(by='Productivity score', ascending=False)

print(sorted_df)

import pandas as pd
df_employee_health  = pd.read_csv('/content/sample_data/Employee_Health.csv')
Marge_df = pd.merge(df_employee_health, df, on='EmployeeID',how='outer')
Marge_df

Marge_df['Gender_x'] = Marge_df['Gender_x'].replace({'Fmale': 'Female'})
Marge_df

Marge_df['Gender_x'] = Marge_df['Gender_x'].replace({'Mle': 'Male'})
Marge_df

# Correlation matrix with dataframe variables
import pandas as pd

df_health = pd.read_csv('/content/sample_data/Employee_Health.csv')

df_health

corr_matrix1 = df_health[['WorkHours', 'SleepHours','ProductivityScore']].corr()
print(corr_matrix1)

# Heatmap for correlation

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(corr_matrix1, annot=True, cmap = 'vlag')
plt.show()

"""**Phyton Visualization**"""

# Importing all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import input file
df = pd.read_csv('/content/sample_data/Employee_Details.csv')
df = df.set_index('Department')
df

Count = Marge_df['Department_y'].value_counts()
Count

Count.plot(kind = 'barh')
plt.show()

gender_stress = Marge_df.groupby('Gender_x')['StressLevel'].mean()
gender_stress

gender_stress.plot(kind = 'bar', figsize=(12,10), color='orange')
plt.show()

# Importing all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import input file
df = pd.read_csv('/content/sample_data/Employee_Health.csv')
df = df.set_index('StressLevel')
df

df.plot(kind = 'bar')

import pandas as pd
import matplotlib.pyplot as plt

df_logingdate = pd.DataFrame({
    'employee_name': ['Megan', 'Katherine', 'Robert', 'Jonathan', 'William'],
    'last_login_date': ['2025-07-05', '2025-02-03', '2025-04-16', '2025-05-23', '2025-01-18']
})
df_logingdate

import matplotlib.pyplot as plt

work_hours = [7, 5, 5, 7, 10, 9, 9, 8]
productivity_score = [43, 85, 76, 74, 70, 89, 60, 55]

plt.scatter(work_hours, productivity_score, color='red', marker='o')
plt.xlabel('Work Hours')
plt.ylabel('Productivity Score')

Marge_df['LastLogin'] = pd.to_datetime(Marge_df['LastLogin'])
Marge_df

Marge_df = Marge_df.sort_values(by='LastLogin')
Marge_df

plt.plot(Marge_df['Name_x'], Marge_df['LastLogin'], marker='o', linestyle='-')
plt.show()